version: '3.7'

services:
  nginx:
    image: ethibox/nginx-proxy:latest
    command: /bin/sh -c "apk add --no-cache curl && cp /etc/nginx/nginx-nextcloud.conf /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 2m
    volumes:
      - ${VOLUME_PATH}nextcloud:/var/www/html:cached
    deploy:
      labels:
        traefik.enable: "true"
        traefik.port: 80
        traefik.frontend.rule: Host:${DOMAIN:-nextcloud.localhost}
        traefik.frontend.headers.customResponseHeaders: "X-Frame-Options: SAMEORIGIN||Strict-Transport-Security: max-age=31536000||Referrer-Policy: no-referrer"
        traefik.frontend.redirect.permanent: "true"
        traefik.frontend.redirect.regex: https://(.*)/.well-known/(card|cal)dav
        traefik.frontend.redirect.replacement: https://$$1/remote.php/dav/
    networks:
      - internal
      - traefik

  app:
    image: nextcloud:${VERSION:-18.0.1-fpm-alpine}
    command:
      - /bin/sh
      - -c
      - |
        sleep 10
        apk add --no-cache sudo
        sudo -u www-data php occ --no-warnings config:system:set trusted_proxies 0 --value="172.xx.0.x"
        php-fpm
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nextcloud}
      - MYSQL_USER=${MYSQL_USER:-nextcloud}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-myp@ssw0rd}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER:-admin}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD:-myp@ssw0rd}
      - NEXTCLOUD_TRUSTED_DOMAINS=${DOMAIN:-nextcloud.localhost} nginx
      - NEXTCLOUD_UPDATE=1
    volumes:
      - ${VOLUME_PATH}nextcloud:/var/www/html:cached
    networks:
      - internal

  mariadb:
    image: mariadb:10.3.12
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-myp@ssw0rd}
      - MYSQL_USER=${MYSQL_USER:-nextcloud}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nextcloud}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-myp@ssw0rd}
    volumes:
      - ${VOLUME_PATH}mariadb:/var/lib/mysql
    networks:
      - internal

volumes:
  nextcloud:
  mariadb:

networks:
  internal:
  traefik:
    external: true
    name: traefik-net
